import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { test } from 'node:test'

const __dirname = dirname(fileURLToPath(import.meta.url))
const readSource = (path: string) => readFileSync(resolve(__dirname, path), 'utf8')

test('aux scheduler frontend exposes lane and migration fields in the API contract', () => {
  const typeSource = readSource('../src/api/types.ts')
  assert.match(typeSource, /model_names:\s*string\[\]/)
  assert.match(typeSource, /lanes:\s*number\[\]\[\]/)
  assert.match(typeSource, /maximum_auto_lane:\s*number/)
  assert.match(typeSource, /migration_status:\s*''\s*\|\s*'needs_migration'/)
  assert.match(typeSource, /lane_accounts:\s*AuxSchedulerLaneView\[\]/)
  assert.match(typeSource, /interface AuxSchedulerMigrationSource/)
  assert.match(typeSource, /legacy_primary_account_ids:\s*number\[\]/)
  assert.match(typeSource, /interface AuxSchedulerAccountInfo\s*\{[\s\S]*?name\?: string[\s\S]*?type\?: string[\s\S]*?status\?: string[\s\S]*?schedulable\?: boolean/)
  assert.doesNotMatch(typeSource, /interface AuxSchedulerRule[^{]*\{[\s\S]*?primary_account_ids:\s*number\[\]/)
  assert.doesNotMatch(typeSource, /interface AuxSchedulerRule[^{]*\{[\s\S]*?backup_account_ids:\s*number\[\]/)
  assert.doesNotMatch(typeSource, /primary_accounts\?: AuxSchedulerAccountInfo\[\]/)
  assert.doesNotMatch(typeSource, /backup_accounts\?: AuxSchedulerAccountInfo\[\]/)
})

test('aux scheduler view distinguishes migration, disabled, and active rules', () => {
  const source = readSource('../src/views/AdminAuxSchedulerView.vue')
  assert.match(source, /needs_migration/)
  assert.match(source, /'需要迁移'/)
  assert.match(source, /'已禁用'/)
  assert.match(source, /:type="statusTagType\(row\)"/)
  assert.match(source, /statusLabel\(row\)/)
  assert.match(source, /migration_status === 'needs_migration'\) return '需要迁移'/)
  assert.match(source, /observedAccountLabel/)
  assert.match(source, /item\.status \|\| 'unknown'/)
  assert.match(source, /'可调度'/)
  assert.match(source, /'不可调度'/)
  assert.match(source, /'未观测'/)
  assert.match(source, /否则不会自动调度/)
  assert.match(source, /lane_accounts/)
  assert.match(source, /model_names/)
  assert.match(source, /未配置模型集合/)
})

test('aux scheduler view provides ordered lane editing and cost disclosure', () => {
  const source = readSource('../src/views/AdminAuxSchedulerView.vue')
  assert.match(source, /form\.model_names/)
  assert.match(source, /form\.lanes/)
  assert.match(source, /form\.maximum_auto_lane/)
  assert.match(source, /添加泳道/)
  assert.match(source, /删除泳道/)
  assert.match(source, />上移<\/el-button>/)
  assert.match(source, />下移<\/el-button>/)
  assert.match(source, /累积开启不等于严格成本隔离/)
  assert.match(source, /model_names:\s*form\.model_names/)
  assert.match(source, /lanes:\s*form\.lanes/)
  assert.match(source, /maximum_auto_lane:\s*form\.maximum_auto_lane/)
})

test('aux scheduler admin API serializes the new lane contract', () => {
  const apiSource = readSource('../src/api/admin.ts')
  const typeSource = readSource('../src/api/types.ts')
  assert.match(apiSource, /model_names:\s*string\[\]/)
  assert.match(apiSource, /lanes:\s*number\[\]\[\]/)
  assert.match(apiSource, /maximum_auto_lane:\s*number/)
  assert.match(typeSource, /maximum_auto_lane:\s*number/)
  assert.match(typeSource, /lanes:\s*number\[\]\[\]/)
})

test('aux scheduler view keeps lifecycle feedback during cleanup and failure', () => {
  const source = readSource('../src/views/AdminAuxSchedulerView.vue')
  assert.match(source, /saving\.value = true/)
  assert.match(source, /catch \(error: any\)/)
  assert.match(source, /ElMessage\.error\(error\?\.message \?\? '保存失败'\)/)
  assert.match(source, /ElMessage\.error\(error\?\.message \?\? '删除失败'\)/)
  assert.match(source, /await loadAll\(\)/)
})

test('aux scheduler runtime contract exposes prefixes, evidence, and blocked state', () => {
  const typeSource = readSource('../src/api/types.ts')
  assert.match(typeSource, /expected_open_through_lane:\s*number/)
  assert.match(typeSource, /observed_open_through_lane:\s*number/)
  assert.match(typeSource, /verified_open_through_lane:\s*number/)
  assert.match(typeSource, /target_open_through_lane:\s*number/)
  assert.match(typeSource, /missing_models\?: string\[\]/)
  assert.match(typeSource, /upgrade_evidence\?: Record<string, unknown> \| null/)
  assert.match(typeSource, /recovery_candidate_lane\?: number \| null/)
  assert.match(typeSource, /recovery_candidate_since\?: string \| null/)
  assert.match(typeSource, /blocked_reason\?: string/)
  assert.match(typeSource, /transition_status:\s*string/)
  assert.match(typeSource, /transition_generation:\s*number/)
})

test('aux scheduler view renders runtime state separately from upstream observations', () => {
  const source = readSource('../src/views/AdminAuxSchedulerView.vue')
  assert.match(source, /expected_open_through_lane/)
  assert.match(source, /verified_open_through_lane/)
  assert.match(source, /missing_models/)
  assert.match(source, /blocked_reason/)
  assert.match(source, /recovery_candidate_lane/)
  assert.match(source, /recovery_candidate_since/)
  assert.match(source, /upgrade_evidence/)
  assert.match(source, /期望/)
  assert.match(source, /观测/)
  assert.match(source, /自动泳道上限/)
  assert.match(source, /累积开启不等于严格成本隔离/)
  assert.match(source, /transitionStatusLabel/)
  assert.match(source, /case 'stable':/)
  assert.match(source, /return '稳定'/)
  assert.match(source, /if \(rule\.model_names\?\.length\) return transitionTagType\(rule\)/)
  assert.match(source, /width="min\(640px, calc\(100vw - 24px\)\)"/)
  assert.match(source, /aux-rule-dialog/)
  assert.match(source, /max-height: calc\(100vh - 48px\)/)
  assert.match(source, /overflow: auto/)
})
